mysql:
  host: 127.0.0.1
  port: 3306
  db: gvb
  config: charset=utf8mb4&parseTime=True&loc=Local
  user: root
  password: huahua521
  log_level: dev
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show_line: true
  log_in_console: ""
system:
  host: 0.0.0.0
  port: 8081
  env: release
site_info:
  created_at: "2023-02-12"
  bei_an: 沪ICP20211010123号-2
  title: Asatsuki Sasori 个人博客
  qq_image: https://p26-passport.byteacctimg.com/img/user-avatar/1f3fba24cec499cb4f124eb9c02c5828~80x80.awebp
  version: 8.0.2
  email: 867700123@qq.com
  wechat_image: https://p26-passport.byteacctimg.com/img/user-avatar/1f3fba24cec499cb4f124eb9c02c5828~80x80.awebp
  name: '@皂化弄人'
  job: 后端开发
  slogan: 赚大钱 开宝马
  slogan_en: earn money buy bmw.
  web: http://liritian.com
  bilibili_url: "111"
  github_url: https://github.com/GStepOne
  gitee_url: "33"
  addr: 上海市浦东新区
qq:
  app_id: "102099599"
  app_key: cFnCSVO4hBe7SddP
  redirect: http://www.liritian.com/login?flag=qq
jwt:
  secret: xxxx
  expires: 48
  issuer: xx
qi_niu:
  access_key: P-8AgS1WqT-BgVSDf1o3oPzs-892QbbNuHectlVo
  secret_key: OcrIEwxlmhZ-huVdC83_x3_bj2tP-cwxmITdM_Nd
  bucket: gin-vue-jack-blog
  cdn: sazz982o7.hd-bkt.clouddn.com
  zone: xx
  size: 5
  prefix: gin
  enable: false
email:
  host: smtp.qq.com
  port: 465
  user: 124307954@qq.com
  password: euudczvnmumnbggb
  default_from_email: 124307954@qq.com
  use_ssl: true
  use_tls: false
upload:
  size: 4
  path: uploads/file
redis:
  ip: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  pool_size: 12
es:
  host: http://127.0.0.1
  port: 9200
  user: ""
  password: ""
chat_group:
  is_anonymous: true
  is_show_time: true
  default_limit: 100
  welcome_title: Jack聊天室
  is_online_people: true
  is_send_image: true
  is_send_file: false
  is_markdown: true
  is_paste: true
  content_length: 0
