mysql:
  host: 127.0.0.1
  port: 3306
  db: gvb
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  user: root
  password: huahua521
  log_level: dev
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show_line: true
  log_in_console: ""
system:
  host: 0.0.0.0
  port: 8081
  env: release
site_info:
  created_at: "2023-02-12"
  bei_an: 沪ICP20211010123号-2
  title: Jack的个人博客
  qq_image: http://liritian.com/static/my/img/footer/qq.png
  version: 6.0.2
  email: 2663456523@qq.com
  wechat_image: http://www.liritian.com/static/my/img/footer/wechat.png
  name: jack
  job: 后端开发
  slogan: 赚大钱 开宝马
  slogan_en: earn money buy bmw
  web: http://liritian.com
  bilibili_url: "111"
  github_url: "222"
  gitee_url: "33"
qq:
  app_id: 102099599
  key: cFnCSVO4hBe7SddP
  redirect: http://www.liritian.com/login?flag=qq
jwt:
  secret: xxxx
  expires: 48
  issuer: xx
qi_niu:
  enable: true
  access_key: P-8AgS1WqT-BgVSDf1o3oPzs-892QbbNuHectlVo
  secret_key: OcrIEwxlmhZ-huVdC83_x3_bj2tP-cwxmITdM_Nd
  bucket: gin-vue-jack-blog
  cdn: sazz982o7.hd-bkt.clouddn.com
  zone: xx
  size: 5
  prefix: "gin"
upload:
  path: uploads/file
  size: 1
email:
  host: smtp.qq.com
  port: 465
  user: "124307954@qq.com"
  password: "euudczvnmumnbggb"
  default_from_email: "124307954@qq.com"
  use_ssl: false
  use_tls: false
redis:
  ip: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  pool_size: 12
